
# CombatStats v@version@ by Kaliber

# » Placeholders
# This plugin supports PlaceholderAPI placeholders which can be found here:
# https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders

# » CombatStats PlaceholderAPI Placeholders
# - %combatstats_kills% - returns the player's kills.
# - %combatstats_deaths% - returns the player's deaths.
# - %combatstats_kd% - returns the player's KD ratio.
# - %combatstats_killstreak% - returns the player's current killstreak.
# - %combatstats_last_kill% - returns the last player they killed.
# - %combatstats_kd_rounded_[decimal-places]% - returns the player's KD rounded. If there is no decimal place specified, the placeholder will default to 2 decimal places
# - %combatstats_placement_<type>_<player-name>% - returns the player's position in the leaderboard type
# - %combatstats_top_<type>_<info>_<position>% - returns the name/value who is at the position specified in the leaderboard type

# <TYPE> - specifies which leaderboard to use: kills/killstreak
# <INFO> - specifies which information to display: player-name/value (value being either the kills or killstreak amount)
# <POSITION> - the position of the leaderboard to get

# *Placeholders with <> - required fields
# *Placeholders with [] - optional fields

# » Internal Placeholders
# - %killer% - get the killer's name
# - %dead% - get the player's name who died

# » Configuration Settings
# messages:
#   player-command-only: (message to be displayed when the command is only for players)
#   player-not-found: (message to be displayed when the player can not be found)
#   reload-command: (reload command message)
#   main-command:
#     - (main command message)
#   help-command:
#     - (help command message)
#   stats-command:
#     - (Displays a message when "/combatstats stats [player]" is run.)
#     - If a player argument is present in the command, the command will return the statistics for that player

# save-data-interval:
# Set the delay between when each task will be executed, in seconds
# Tasks include: Saving player data to file and updating leaderboards
# This setting will only change upon restart

# rewards:
#   enabled: (Specify whether rewards should be enabled or not)
#   killer:
#     commands:
#       - (execute commands for the killer)
#     messages:
#       - (send messages to the killer)
#   player:
#     commands:
#       - (execute commands for the dead player)
#     messages:
#      - (send messages to the dead player)

messages:
  player-command-only: '&7Only players can execute this command.'
  player-not-found: '&7Player not found.'
  no-permission: '&cNo permission!'
  command-wrong-usage: '&cWrong Usage! &a/cstats help'
  reload-command: '&bConfig reloaded.'
  main-command:
    - ''
    - '&bCombatStats &7version &f@version@'
    - '&7Created by: &bKaliber'
    - ''
  help-command:
    - ''
    - '&9CombatStats Help &8(&7v@version@&8)'
    - '&b/combatstats &8- &7Display plugin information'
    - '&b/combatstats help &8- &7Display plugin commands'
    - '&b/combatstats reload &8- &7Reload configuration file'
    - '&b/combatstats stats [player] &8- &7Display player statistics'
    - ''
  stats-command:
    - ''
    - '&9%player_name%''s Stats &8- '
    - '&bKillstreak&7: &f%combatstats_killstreak%'
    - ''

save-data-interval: 300

rewards:
  enabled: true
  killer:
    commands:
      - 'give %player_name% diamond 10'
    messages:
      - '&fYou killed &b%dead%&f!'
  player:
    commands:
    - 'eco take %player_name% 10'
    messages:
    - '&fYou were killed by &c%killer%'
