
# CombatStats v@version@ by Kaliber

# Spigot Page: https://spigotmc.org/resources/combatstats.94932/
# Github Link: https://github.com/Kqliber/CombatStats
# Create an issue on GitHub: https://github.com/Kqliber/CombatStats/issues

# » Placeholders
# This plugin supports PlaceholderAPI placeholders which can be found here:
# https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders

# » CombatStats PlaceholderAPI Placeholders
# - %combatstats_kills% - returns the player's kills.
# - %combatstats_deaths% - returns the player's deaths.
# - %combatstats_kdr% - returns the player's KD ratio.
# - %combatstats_killstreak% - returns the player's current killstreak.
# - %combatstats_highestkillstreak% - returns the player's highest killstreak.
# - %combatstats_last_kill% - returns the last player they killed.
# - %combatstats_kdr_rounded_[decimal-places]% - returns the player's KDR rounded. If there is no decimal place specified, the placeholder will default to 2 decimal places
# - %combatstats_placement_<type>_<player>% - returns the player's position in the leaderboard type
# - %combatstats_top_<type>_<info>_<position>% - returns the name/value who is at the position specified in the leaderboard type

# <TYPE> - specifies which leaderboard to use:
#  - kills_daily
#  - kills_weekly
#  - kills_monthly
#  - kills_alltime
#  - kdr_alltime
#  - killstreak_alltime
#  - highestkillstreak_alltime
# (maybe timed leaderboard for kdr, killstreak & highestkillstreak soon?)
# <INFO> - specifies which information to display: name/value (name being the player's name, or value being the value retrieved from the specified leaderboard type)
# <POSITION> - the position of the leaderboard to get

# *Placeholders with <> - required fields
# *Placeholders with [] - optional fields

# » Internal Placeholders
# - %killer% - get the killer's name
# - %dead% - get the player's name who died

# » Configuration Settings

# settings:
#   save-data-interval: (Set the delay between when each task will be executed, in seconds)
#   storage-method: (Set the method for storing data: Available methods: json)

# messages:
#   player-command-only: (message to be displayed when the command is only for players)
#   player-not-found: (message to be displayed when the player can not be found)
#   reload-command: (reload command message)
#   main-command:
#     - (main command message)
#   help-command:
#     - (help command message)
#   stats-command:
#     - (Displays a message when "/combatstats stats [player]" is run.)
#     - If a player argument is present in the command, the command will return the statistics for that player

# rewards:
#   enabled: (Specify whether rewards should be enabled or not)
#   killer:
#     commands:
#       - (execute commands for the killer)
#     messages:
#       - (send messages to the killer)
#   player:
#     commands:
#       - (execute commands for the dead player)
#     messages:
#      - (send messages to the dead player)
settings:
  save-data-interval: 300
  storage-method: json
messages:
  player-command-only: '&7Only players can execute this command.'
  player-not-found: '&7Player not found.'
  no-permission: '&cNo permission!'
  command-wrong-usage: '&cWrong Usage! &a/cstats help'
  reload-command: '&bConfig reloaded.'
  main-command:
    - ''
    - '&bCombatStats &7version &f@version@'
    - '&7Created by: &bKaliber'
    - ''
  help-command:
    - ''
    - '&9CombatStats Help &8(&7v@version@&8)'
    - '&b/combatstats &8- &7Display plugin information'
    - '&b/combatstats help &8- &7Display plugin commands'
    - '&b/combatstats reload &8- &7Reload configuration file'
    - '&b/combatstats stats [player] &8- &7Display player statistics'
    - ''
  stats-command:
    - ''
    - '&9%player_name%''s Stats &8- '
    - '&bKillstreak&7: &f%combatstats_killstreak%'
    - ''

rewards:
  enabled: true
  killer:
    commands:
      - 'give %player_name% diamond 10'
    messages:
      - '&fYou killed &b%dead%&f!'
  player:
    commands:
    - 'eco take %player_name% 10'
    messages:
    - '&fYou were killed by &c%killer%'
  killstreaks:
    5:
      commands:
        - 'broadcast &b%player_name% &fis on a &b%combatstats_killstreak% &fkillstreak!'
      messages:
        - '&fYou are on a &b%combatstats_killstreak% &fkillstreak!'
